use crate::nes::cpu::opcodes::*;
use crate::nes::cpu::AddressMode;
use crate::nes::cpu::address_modes::*;

pub(crate) type OpcodeHandler = fn(&mut super::Cpu) -> u32;

// Lookup table for all 6502 opcodes
pub(crate) static OPCODE_TABLE: [Option<OpcodeHandler>; 256] = [
    // 0x00
    Some(|cpu| Brk::from_implied(cpu)),
    Some(|cpu| Ora::from_address(cpu, AddressMode::IndirectX)),
    None,
    None,
    None,
    Some(|cpu| Ora::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Asl::from_address(cpu, AddressMode::ZeroPage)),
    None,
    Some(|cpu| Php::from_implied(cpu)),
    Some(|cpu| Ora::from_immediate(cpu)),
    Some(|cpu| Asl::from_accumulator(cpu)),
    None,
    None,
    Some(|cpu| Ora::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Asl::from_address(cpu, AddressMode::Absolute)),
    None,
    // 0x10
    Some(|cpu| Bpl::from_relative(cpu)),
    Some(|cpu| Ora::from_address(cpu, AddressMode::IndirectY)),
    None,
    None,
    None,
    Some(|cpu| Ora::from_address(cpu, AddressMode::ZeroPageX)),
    Some(|cpu| Asl::from_address(cpu, AddressMode::ZeroPageX)),
    None,
    Some(|cpu| Clc::from_implied(cpu)),
    Some(|cpu| Ora::from_address(cpu, AddressMode::AbsoluteY)),
    None,
    None,
    None,
    Some(|cpu| Ora::from_address(cpu, AddressMode::AbsoluteX)),
    Some(|cpu| Asl::from_address(cpu, AddressMode::AbsoluteX)),
    None,
    // 0x20
    Some(|cpu| Jsr::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| And::from_address(cpu, AddressMode::IndirectX)),
    None,
    None,
    Some(|cpu| Bit::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| And::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Rol::from_address(cpu, AddressMode::ZeroPage)),
    None,
    Some(|cpu| Plp::from_implied(cpu)),
    Some(|cpu| And::from_immediate(cpu)),
    Some(|cpu| Rol::from_accumulator(cpu)),
    None,
    Some(|cpu| Bit::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| And::from_address(cpu, AddressMode::Absolute)),
    None,
    None,
    // 0x30
    Some(|cpu| Bmi::from_relative(cpu)),
    Some(|cpu| And::from_address(cpu, AddressMode::IndirectY)),
    None,
    None,
    None,
    Some(|cpu| And::from_address(cpu, AddressMode::ZeroPageX)),
    None,
    None,
    Some(|cpu| Sec::from_implied(cpu)),
    Some(|cpu| And::from_address(cpu, AddressMode::AbsoluteY)),
    None,
    None,
    None,
    Some(|cpu| And::from_address(cpu, AddressMode::AbsoluteX)),
    None,
    None,
    // 0x40
    Some(|cpu| Rti::from_implied(cpu)),
    Some(|cpu| Eor::from_address(cpu, AddressMode::IndirectX)),
    None,
    None,
    None,
    Some(|cpu| Eor::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Lsr::from_address(cpu, AddressMode::ZeroPage)),
    None,
    Some(|cpu| Pha::from_implied(cpu)),
    Some(|cpu| Eor::from_immediate(cpu)),
    Some(|cpu| Lsr::from_accumulator(cpu)),
    None,
    Some(|cpu| Jmp::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Eor::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Lsr::from_address(cpu, AddressMode::Absolute)),
    None,
    // 0x50
    Some(|cpu| Bvc::from_relative(cpu)),
    Some(|cpu| Eor::from_address(cpu, AddressMode::IndirectY)),
    None,
    None,
    None,
    Some(|cpu| Eor::from_address(cpu, AddressMode::ZeroPageX)),
    Some(|cpu| Lsr::from_address(cpu, AddressMode::ZeroPageX)),
    None,
    Some(|cpu| Cli::from_implied(cpu)),
    Some(|cpu| Eor::from_address(cpu, AddressMode::AbsoluteY)),
    None,
    None,
    None,
    Some(|cpu| Eor::from_address(cpu, AddressMode::AbsoluteX)),
    Some(|cpu| Lsr::from_address(cpu, AddressMode::AbsoluteX)),
    None,
    // 0x60
    Some(|cpu| Rts::from_implied(cpu)),
    Some(|cpu| Adc::from_address(cpu, AddressMode::IndirectX)),
    None,
    None,
    None,
    Some(|cpu| Adc::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Ror::from_address(cpu, AddressMode::ZeroPage)),
    None,
    Some(|cpu| Pla::from_implied(cpu)),
    Some(|cpu| Adc::from_immediate(cpu)),
    Some(|cpu| Ror::from_accumulator(cpu)),
    None,
    Some(|cpu| Jmp::from_address(cpu, AddressMode::Indirect)),
    Some(|cpu| Adc::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Ror::from_address(cpu, AddressMode::Absolute)),
    None,
    // 0x70
    Some(|cpu| Bvs::from_relative(cpu)),
    Some(|cpu| Adc::from_address(cpu, AddressMode::IndirectY)),
    None,
    None,
    None,
    Some(|cpu| Adc::from_address(cpu, AddressMode::ZeroPageX)),
    None,
    None,
    Some(|cpu| Sei::from_implied(cpu)),
    Some(|cpu| Adc::from_address(cpu, AddressMode::AbsoluteY)),
    None,
    None,
    None,
    Some(|cpu| Adc::from_address(cpu, AddressMode::AbsoluteX)),
    Some(|cpu| Ror::from_address(cpu, AddressMode::AbsoluteX)),
    None,
    // 0x80
    None,
    None,
    None,
    None,
    Some(|cpu| Sty::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Sta::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Stx::from_address(cpu, AddressMode::ZeroPage)),
    None,
    Some(|cpu| Dey::from_implied(cpu)),
    None,
    Some(|cpu| Txa::from_implied(cpu)),
    None,
    Some(|cpu| Sty::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Sta::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Stx::from_address(cpu, AddressMode::Absolute)),
    None,
    // 0x90
    Some(|cpu| Bcc::from_relative(cpu)),
    Some(|cpu| Sta::from_address(cpu, AddressMode::IndirectY)),
    None,
    None,
    Some(|cpu| Sty::from_address(cpu, AddressMode::ZeroPageX)),
    Some(|cpu| Sta::from_address(cpu, AddressMode::ZeroPageX)),
    Some(|cpu| Stx::from_address(cpu, AddressMode::ZeroPageY)),
    None,
    Some(|cpu| Tya::from_implied(cpu)),
    Some(|cpu| Sta::from_address(cpu, AddressMode::AbsoluteY)),
    Some(|cpu| Txs::from_implied(cpu)),
    None,
    None,
    Some(|cpu| Sta::from_address(cpu, AddressMode::AbsoluteX)),
    None,
    None,
    // 0xA0
    Some(|cpu| Ldy::from_immediate(cpu)),
    Some(|cpu| Lda::from_address(cpu, AddressMode::IndirectX)),
    Some(|cpu| Ldx::from_immediate(cpu)),
    None,
    Some(|cpu| Ldy::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Lda::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Ldx::from_address(cpu, AddressMode::ZeroPage)),
    None,
    Some(|cpu| Tay::from_implied(cpu)),
    Some(|cpu| Lda::from_immediate(cpu)),
    Some(|cpu| Tax::from_implied(cpu)),
    None,
    Some(|cpu| Ldy::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Lda::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Ldx::from_address(cpu, AddressMode::Absolute)),
    None,
    // 0xB0
    Some(|cpu| Bcs::from_relative(cpu)),
    Some(|cpu| Lda::from_address(cpu, AddressMode::IndirectY)),
    None,
    None,
    Some(|cpu| Ldy::from_address(cpu, AddressMode::ZeroPageX)),
    Some(|cpu| Lda::from_address(cpu, AddressMode::ZeroPageX)),
    Some(|cpu| Ldx::from_address(cpu, AddressMode::ZeroPageY)),
    None,
    Some(|cpu| Clv::from_implied(cpu)),
    Some(|cpu| Lda::from_address(cpu, AddressMode::AbsoluteY)),
    Some(|cpu| Tsx::from_address(cpu, AddressMode::Implied)),
    None,
    Some(|cpu| Ldy::from_address(cpu, AddressMode::AbsoluteX)),
    Some(|cpu| Lda::from_address(cpu, AddressMode::AbsoluteX)),
    Some(|cpu| Ldy::from_address(cpu, AddressMode::AbsoluteY)),
    None,
    // 0xC0
    Some(|cpu| Cpy::from_immediate(cpu)),
    Some(|cpu| Cmp::from_address(cpu, AddressMode::IndirectX)),
    None,
    None,
    Some(|cpu| Cpy::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Cmp::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Dec::from_address(cpu, AddressMode::ZeroPage)),
    None,
    Some(|cpu| Iny::from_implied(cpu)),
    Some(|cpu| Cmp::from_immediate(cpu)),
    Some(|cpu| Dex::from_implied(cpu)),
    None,
    Some(|cpu| Cpy::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Cmp::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Dec::from_address(cpu, AddressMode::Absolute)),
    None,
    // 0xD0
    Some(|cpu| Bne::from_relative(cpu)),
    Some(|cpu| Cmp::from_address(cpu, AddressMode::IndirectY)),
    None,
    None,
    None,
    Some(|cpu| Cmp::from_address(cpu, AddressMode::ZeroPageX)),
    Some(|cpu| Dec::from_address(cpu, AddressMode::ZeroPageX)),
    None,
    Some(|cpu| Cld::from_implied(cpu)),
    Some(|cpu| Cmp::from_address(cpu, AddressMode::AbsoluteY)),
    None,
    None,
    None,
    Some(|cpu| Cmp::from_address(cpu, AddressMode::AbsoluteX)),
    Some(|cpu| Dec::from_address(cpu, AddressMode::AbsoluteX)),
    None,
    // 0xE0
    Some(|cpu| Cpx::from_immediate(cpu)),
    Some(|cpu| Sbc::from_address(cpu, AddressMode::IndirectX)),
    None,
    None,
    Some(|cpu| Cpx::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Sbc::from_address(cpu, AddressMode::ZeroPage)),
    Some(|cpu| Inc::from_address(cpu, AddressMode::ZeroPage)),
    None,
    Some(|cpu| Inx::from_implied(cpu)),
    Some(|cpu| Sbc::from_immediate(cpu)),
    Some(|_| 2), // NOP
    None,
    Some(|cpu| Cpx::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Sbc::from_address(cpu, AddressMode::Absolute)),
    Some(|cpu| Inc::from_address(cpu, AddressMode::Absolute)),
    None,
    // 0xF0
    Some(|cpu| Beq::from_relative(cpu)),
    Some(|cpu| Sbc::from_address(cpu, AddressMode::IndirectY)),
    None,
    None,
    None,
    Some(|cpu| Sbc::from_address(cpu, AddressMode::ZeroPageX)),
    Some(|cpu| Inc::from_address(cpu, AddressMode::ZeroPageX)),
    None,
    Some(|cpu| Sed::from_implied(cpu)),
    Some(|cpu| Sbc::from_address(cpu, AddressMode::AbsoluteY)),
    None,
    None,
    None,
    Some(|cpu| Sbc::from_address(cpu, AddressMode::AbsoluteX)),
    Some(|cpu| Inc::from_address(cpu, AddressMode::AbsoluteX)),
    None,
];
