# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debugger_server.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "OkReply" do
    optional :message, :string, 1
  end
  add_message "StopRequest" do
    optional :program_counter, :uint32, 1
  end
  add_message "ContinueRequest" do
  end
  add_message "PingRequest" do
    optional :message, :string, 1
  end
  add_message "DisassembleRequest" do
    optional :address, :uint32, 1
    optional :count, :uint64, 2
  end
  add_message "DisassembleMsg" do
    optional :line, :string, 1
    optional :instruction_width, :uint32, 2
    optional :address, :uint32, 3
  end
  add_message "DisassembleReply" do
    optional :length, :uint64, 1
    repeated :disassembly, :message, 2, "DisassembleMsg"
    optional :last_error, :string, 5
  end
end

OkReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("OkReply").msgclass
StopRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("StopRequest").msgclass
ContinueRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ContinueRequest").msgclass
PingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("PingRequest").msgclass
DisassembleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("DisassembleRequest").msgclass
DisassembleMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("DisassembleMsg").msgclass
DisassembleReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("DisassembleReply").msgclass
